const NAVLINKS = [{ id: 'base' }, { id: 'advanced' }];

const INITIAL_STATE_DATA = {
  actionType: null,
  attributeName: null,
  attributeType: null,
  dynamicZoneTarget: null,
  forTarget: null,
  headerDisplayCategory: null,
  headerDisplayName: null,
  headerDisplaySubCategory: null,
  modalType: null,
  pathToSchema: [],
  settingType: null,
  step: null,
  subTargetUid: null,
  targetUid: null,
  headerId: null,
  header_label_1: null,
  header_icon_name_1: null,
  header_icon_isCustom_1: null,
  header_info_category_1: null,
  header_info_name_1: null,
  header_label_2: null,
  header_icon_name_2: null,
  header_icon_isCustom_2: null,
  header_info_category_2: null,
  header_info_name_2: null,
  header_label_3: null,
  header_icon_name_3: null,
  header_icon_isCustom_3: null,
  header_info_category_3: null,
  header_info_name_3: null,
};

export { NAVLINKS, INITIAL_STATE_DATA };
