# This file runs the given workflows when an affected file is found, otherwise it passes as skipped

backend:
  - 'packages/**/server/**/*.(js|ts)'
  - 'packages/**/strapi-server.js'
  - 'packages/{utils,generators,cli,providers}/**'
  - 'packages/core/*/{lib,bin,ee,src}/**'
  - 'packages/core/database/**'
  - 'jest-preset.back.js'
frontend:
  - 'packages/**/admin/src/**'
  - 'packages/**/admin/ee/admin/**'
  - 'packages/**/strapi-admin.js'
  - 'packages/admin-test-utils/**'
  - 'jest-preset.front.js'
  - 'fileTransformer.js'
api:
  - 'tests/api/**'
e2e:
  - 'tests/e2e/**'
  - 'playwright.base.config.js'
cli:
  - 'tests/cli/**'

# TODO: this needs a lot more in it
all_tests:
  - 'packages/**/package.json'
  - '.github/actions/yarn-nm-install/*.yml'
  - '.github/workflows/**'
  - 'yarn.lock'
  - 'jest.config.js'

# note that docs only runs on this, it doesn't include all_tests above
docs:
  - 'docs/**'
  - '**.mdx?'
