# This file determines when jobs should run or skipped based on which files were modified

backend:
  - 'packages/**/server/**/*.(js|ts|json)'
  - 'packages/**/strapi-server.js'
  - 'packages/{utils,generators,cli,providers}/**'
  - 'packages/core/*/{lib,bin,ee,src}/**'
  - 'packages/core/database/**'
  - 'jest-preset.back.js'
frontend:
  - 'packages/**/admin/src/**'
  - 'packages/**/admin/ee/admin/**'
  - 'packages/**/strapi-admin.js'
  - 'packages/admin-test-utils/**'
  - 'jest-preset.front.js'
  - 'fileTransformer.js'
api:
  - 'tests/scripts/run-api-tests.js'
  - 'tests/scripts/generate-test-app.js'
  - 'tests/api/**'
e2e:
  - 'tests/scripts/run-e2e-tests.js'
  - 'tests/e2e/**'
  - 'playwright.base.config.js'
cli:
  - 'tests/scripts/run-cli-tests.js'
  - 'tests/cli/**'
docs:
  - 'docs/**'
  - '**.mdx?'

# Changes to these files cause all jobs to run
# TODO: this needs a lot more in it
global:
  - 'packages/**/package.json'
  - '.github/actions/yarn-nm-install/*.yml'
  - '.github/workflows/**'
  - 'yarn.lock'
  - 'jest.config.js'
  - 'package.json'
