const INITIAL_STATE_DATA = {
  actionType: null,
  attributeName: null,
  attributeType: null,
  dynamicZoneTarget: null,
  forTarget: null,
  modalType: null,
  kind: null,
  pathToSchema: [],
  settingType: null,
  step: null,
  targetUid: null,
  headerId: null,
  header_label_1: null,
  header_info_category_1: null,
  header_info_name_1: null,
  header_label_2: null,
  header_info_category_2: null,
  header_info_name_2: null,
  header_label_3: null,
  header_info_category_3: null,
  header_info_name_3: null,
  header_label_4: null,
  header_info_category_4: null,
  header_info_name_4: null,
  header_label_5: null,
  header_info_category_5: null,
  header_info_name_5: null,
};

export { INITIAL_STATE_DATA };
