# Use an empty semver range prefix
defaultSemverRangePrefix: ''

# Use the `node-modules` linker
nodeLinker: node-modules

# Prefer interactive prompts where applicable
preferInteractive: true

# Define the path to the Yarn binary
yarnPath: .yarn/releases/yarn-4.5.0.cjs
