# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Issues helper — lock issue (pinned)
description: Pinned wrapper — see ../../README.md
inputs:
  token:
    required: true
  issue-number:
    required: true
  lock-reason:
    required: true
runs:
  using: composite
  steps:
    - uses: actions-cool/issues-helper@200c78641dbf33838311e5a1e0c31bbdb92d7cf0
      with:
        actions: lock-issue
        token: ${{ inputs.token }}
        issue-number: ${{ inputs.issue-number }}
        lock-reason: ${{ inputs.lock-reason }}
