/**
 * Extra optimizeDeps.include entries for the getstarted monorepo example only.
 * Not applied to consumer apps (missing packages would break their builds).
 *
 * @internal
 */
export const ADMIN_VITE_MONOREPO_EXAMPLE_OPTIMIZE_INCLUDE = [
  '@dnd-kit/core',
  '@dnd-kit/sortable',
  '@dnd-kit/utilities',
  '@dnd-kit/modifiers',
  '@radix-ui/react-toolbar',
  'codemirror5',
  'codemirror5/addon/display/placeholder',
  'date-fns-tz',
  'date-fns/format',
  'date-fns/formatISO',
  'highlight.js',
  'lodash/capitalize',
  'lodash/fp',
  'lodash/groupBy',
  'lodash/has',
  'lodash/isNil',
  'lodash/locale',
  'lodash/map',
  'lodash/mapValues',
  'lodash/pull',
  'lodash/size',
  'lodash/sortBy',
  'lodash/tail',
  'lodash/toLower',
  'lodash/toNumber',
  'lodash/toString',
  'lodash/truncate',
  'lodash/uniq',
  'lodash/upperFirst',
  'markdown-it',
  'markdown-it-abbr',
  'markdown-it-container',
  'markdown-it-deflist',
  'markdown-it-emoji',
  'markdown-it-footnote',
  'markdown-it-ins',
  'markdown-it-mark',
  'markdown-it-sub',
  'markdown-it-sup',
  'react-colorful',
  'react-dnd-html5-backend',
  'react-window',
  'semver',
  'semver/functions/lt',
  'semver/functions/valid',
  'slate',
  'slate-history',
  'slate-react',
  'motion',
] as const;
