import { useEffect, useState } from 'react';

import { Box, Checkbox, Flex, Typography } from '@strapi/design-system';
import { useFetchClient } from '@strapi/admin/strapi-admin';
import get from 'lodash/get';
import { useIntl } from 'react-intl';

import { getTranslation } from '../utils/getTranslation';

interface SpaceOption {
  id: number;
  slug: string;
  name: string;
  color: string | null;
}

interface SpaceVisibilityProps {
  intlLabel?: { id: string; defaultMessage: string };
  description?: { id: string; defaultMessage: string };
  name: string;
  onChange: (input: { target: { name: string; value: string[]; type: string } }) => void;
  value?: string[];
  /** Provided by FormModal — used to gate visibility on the sibling scope field. */
  modifiedData?: any;
}

/**
 * "Visible in spaces" — checkbox list shown in the Content-Type Builder's
 * Advanced settings when the Spaces tenant scope is set to `space`. Stores
 * an array of space slugs at `pluginOptions.spaces.visibleIn`. Empty value
 * = visible in every space (the default).
 *
 * Implementation note: do NOT wrap multiple Checkboxes in one Field.Root —
 * Field.Root provides a single id via context, and the design-system Checkbox
 * (`packages/design-system/.../Checkbox.tsx`) auto-links the label to that id
 * via `htmlFor`. With many checkboxes sharing one id, clicking any label
 * toggles the first checkbox instead of the intended one. Each checkbox here
 * owns its own id (autogenerated by the design-system) so the htmlFor link is
 * always correct.
 */
export const SpaceVisibility = ({
  intlLabel,
  description,
  name,
  onChange,
  value,
  modifiedData,
}: SpaceVisibilityProps) => {
  const { formatMessage } = useIntl();
  const { get: fetchGet } = useFetchClient();
  const [spaces, setSpaces] = useState<SpaceOption[] | null>(null);
  const [available, setAvailable] = useState(true);

  useEffect(() => {
    let cancelled = false;
    fetchGet<SpaceOption[]>('/spaces/mine')
      .then((res) => {
        if (cancelled) return;
        setSpaces(Array.isArray(res.data) ? res.data : []);
      })
      .catch(() => {
        if (cancelled) return;
        setAvailable(false);
      });
    return () => {
      cancelled = true;
    };
  }, [fetchGet]);

  // Only show when the sibling scope field at `pluginOptions.spaces.scope` is "space".
  const scope = get(modifiedData, ['pluginOptions', 'spaces', 'scope']);
  if (scope !== 'space') return null;
  if (!available) return null;
  if (!spaces || spaces.length === 0) return null;

  const safeValue: string[] = Array.isArray(value) ? value : [];
  const isAllSelected = safeValue.length === 0 || safeValue.length === spaces.length;
  const isChecked = (slug: string) => isAllSelected || safeValue.includes(slug);

  const emit = (next: string[]) => {
    // Normalize "all selected" to an empty array — semantic shortcut for "visible everywhere".
    const normalized = next.length === spaces.length ? [] : next;
    onChange({ target: { name, value: normalized, type: 'checkbox' } });
  };

  const handleCheckedChange = (slug: string, checked: boolean) => {
    if (checked) {
      if (isAllSelected) {
        emit(spaces.map((s) => s.slug));
        return;
      }
      if (safeValue.includes(slug)) return;
      emit([...safeValue, slug]);
      return;
    }
    if (isAllSelected) {
      emit(spaces.filter((s) => s.slug !== slug).map((s) => s.slug));
      return;
    }
    emit(safeValue.filter((s) => s !== slug));
  };

  const label = intlLabel
    ? formatMessage(intlLabel)
    : formatMessage({
        id: getTranslation('ctb.visibleIn.label'),
        defaultMessage: 'Visible in spaces',
      });
  const hint = description ? formatMessage(description) : '';

  return (
    <Flex direction="column" alignItems="stretch" gap={2}>
      <Typography variant="pi" fontWeight="bold" textColor="neutral800">
        {label}
      </Typography>
      {hint && (
        <Typography variant="pi" textColor="neutral600">
          {hint}
        </Typography>
      )}
      <Flex direction="column" alignItems="stretch" gap={2} paddingTop={2}>
        {spaces.map((space) => (
          <Flex key={space.slug} alignItems="center" gap={2}>
            <Checkbox
              id={`space-visibility-${space.slug}`}
              name={`${name}-${space.slug}`}
              checked={isChecked(space.slug)}
              onCheckedChange={(checked) =>
                handleCheckedChange(space.slug, checked === true)
              }
            >
              {space.name}
            </Checkbox>
            <Box
              width="8px"
              height="8px"
              borderRadius="50%"
              background={space.color ?? 'neutral300'}
              shrink={0}
            />
          </Flex>
        ))}
        {isAllSelected && (
          <Typography variant="pi" textColor="neutral500">
            {formatMessage({
              id: getTranslation('ctb.visibleIn.all'),
              defaultMessage: 'Currently visible in every space.',
            })}
          </Typography>
        )}
      </Flex>
    </Flex>
  );
};
