/*
 *
 * App constants
 *
 */

export const ADD_ATTRIBUTE_RELATION =
  'ContentTypeBuilder/App/ADD_ATTRIBUTE_RELATION';
export const ADD_ATTRIBUTE_RELATION_GROUP =
  'ContentTypeBuilder/App/ADD_ATTRIBUTE_RELATION_GROUP';
export const ADD_ATTRIBUTE_TO_EXISITING_CONTENT_TYPE =
  'ContentTypeBuilder/App/ADD_ATTRIBUTE_TO_EXISITING_CONTENT_TYPE';
export const ADD_ATTRIBUTE_TO_EXISTING_GROUP =
  'ContentTypeBuilder/App/ADD_ATTRIBUTE_TO_EXISTING_GROUP';
export const ADD_ATTRIBUTE_TO_TEMP_CONTENT_TYPE =
  'ContentTypeBuilder/App/ADD_ATTRIBUTE_TO_TEMP_CONTENT_TYPE';
export const ADD_ATTRIBUTE_TO_TEMP_GROUP =
  'ContentTypeBuilder/App/ADD_ATTRIBUTE_TO_TEMP_GROUP';
export const CANCEL_NEW_CONTENT_TYPE =
  'ContentTypeBuilder/App/CANCEL_NEW_CONTENT_TYPE';
export const CLEAR_TEMPORARY_ATTRIBUTE =
  'ContentTypeBuilder/App/CLEAR_TEMPORARY_ATTRIBUTE';
export const CLEAR_TEMPORARY_ATTRIBUTE_GROUP =
  'ContentTypeBuilder/App/CLEAR_TEMPORARY_ATTRIBUTE_GROUP';
export const CLEAR_TEMPORARY_ATTRIBUTE_RELATION =
  'ContentTypeBuilder/App/CLEAR_TEMPORARY_ATTRIBUTE_RELATION';
export const CLEAR_TEMPORARY_ATTRIBUTE_RELATION_GROUP =
  'ContentTypeBuilder/App/CLEAR_TEMPORARY_ATTRIBUTE_RELATION_GROUP';
export const CREATE_TEMP_CONTENT_TYPE =
  'ContentTypeBuilder/App/CREATE_TEMP_CONTENT_TYPE';
export const CREATE_TEMP_GROUP = 'ContentTypeBuilder/App/CREATE_TEMP_GROUP';
export const DELETE_GROUP = 'ContentTypeBuilder/App/DELETE_GROUP';
export const DELETE_GROUP_ATTRIBUTE =
  'ContentTypeBuilder/App/DELETE_GROUP_ATTRIBUTE';
export const DELETE_GROUP_SUCCEEDED =
  'ContentTypeBuilder/App/DELETE_GROUP_SUCCEEDED';
export const DELETE_MODEL = 'ContentTypeBuilder/App/DELETE_MODEL';
export const DELETE_MODEL_ATTRIBUTE =
  'ContentTypeBuilder/App/DELETE_MODEL_ATTRIBUTE';
export const DELETE_MODEL_SUCCEEDED =
  'ContentTypeBuilder/App/DELETE_MODEL_SUCCEEDED';
export const DELETE_TEMPORARY_MODEL =
  'ContentTypeBuilder/App/DELETE_TEMPORARY_MODEL';
export const DELETE_TEMPORARY_GROUP =
  'ContentTypeBuilder/App/DELETE_TEMPORARY_GROUP';
export const GET_DATA = 'ContentTypeBuilder/App/GET_DATA';
export const GET_DATA_SUCCEEDED = 'ContentTypeBuilder/App/GET_DATA_SUCCEEDED';
export const ON_CHANGE_EXISTING_CONTENT_TYPE_MAIN_INFOS =
  'ContentTypeBuilder/App/ON_CHANGE_EXISTING_CONTENT_TYPE_MAIN_INFOS';
export const ON_CHANGE_EXISTING_GROUP_MAIN_INFOS =
  'ContentTypeBuilder/App/ON_CHANGE_EXISTING_GROUP_MAIN_INFOS';
export const ON_CHANGE_NEW_CONTENT_TYPE_MAIN_INFOS =
  'ContentTypeBuilder/App/ON_CHANGE_NEW_CONTENT_TYPE_MAIN_INFOS';
export const ON_CHANGE_NEW_GROUP_MAIN_INFOS =
  'ContentTypeBuilder/App/ON_CHANGE_NEW_GROUP_MAIN_INFOS';
export const ON_CHANGE_ATTRIBUTE = 'ContentTypeBuilder/App/ON_CHANGE_ATTRIBUTE';
export const ON_CHANGE_ATTRIBUTE_GROUP =
  'ContentTypeBuilder/App/ON_CHANGE_ATTRIBUTE_GROUP';
export const ON_CHANGE_RELATION = 'ContentTypeBuilder/App/ON_CHANGE_RELATION';
export const ON_CHANGE_RELATION_GROUP =
  'ContentTypeBuilder/App/ON_CHANGE_RELATION_GROUP';
export const ON_CHANGE_RELATION_NATURE =
  'ContentTypeBuilder/App/ON_CHANGE_RELATION_NATURE';
export const ON_CHANGE_RELATION_NATURE_GROUP =
  'ContentTypeBuilder/App/ON_CHANGE_RELATION_NATURE_GROUP';
export const ON_CHANGE_RELATION_TARGET =
  'ContentTypeBuilder/App/ON_CHANGE_RELATION_TARGET';
export const ON_CHANGE_RELATION_TARGET_GROUP =
  'ContentTypeBuilder/App/ON_CHANGE_RELATION_TARGET_GROUP';
export const RESET_NEW_CONTENT_TYPE_MAIN_INFOS =
  'ContentTypeBuilder/App/RESET_NEW_CONTENT_TYPE_MAIN_INFOS';
export const RESET_EDIT_EXISTING_CONTENT_TYPE =
  'ContentTypeBuilder/App/RESET_EDIT_EXISTING_CONTENT_TYPE';
export const RESET_EXISTING_CONTENT_TYPE_MAIN_INFOS =
  'ContentTypeBuilder/App/RESET_EXISTING_CONTENT_TYPE_MAIN_INFOS';
export const RESET_EDIT_EXISTING_GROUP =
  'ContentTypeBuilder/App/RESET_EDIT_EXISTING_GROUP';
export const RESET_EXISTING_GROUP_MAIN_INFOS =
  'ContentTypeBuilder/App/RESET_EXISTING_GROUP_MAIN_INFOS';
export const RESET_EDIT_TEMP_CONTENT_TYPE =
  'ContentTypeBuilder/App/RESET_EDIT_TEMP_CONTENT_TYPE';
export const RESET_EDIT_TEMP_GROUP =
  'ContentTypeBuilder/App/RESET_EDIT_TEMP_GROUP';
export const RESET_PROPS = 'ContentTypeBuilder/App/RESET_PROPS';
export const SAVE_EDITED_ATTRIBUTE =
  'ContentTypeBuilder/App/SAVE_EDITED_ATTRIBUTE';
export const SAVE_EDITED_ATTRIBUTE_GROUP =
  'ContentTypeBuilder/App/SAVE_EDITED_ATTRIBUTE_GROUP';
export const SAVE_EDITED_ATTRIBUTE_RELATION =
  'ContentTypeBuilder/App/SAVE_EDITED_ATTRIBUTE_RELATION';
export const SAVE_EDITED_ATTRIBUTE_RELATION_GROUP =
  'ContentTypeBuilder/App/SAVE_EDITED_ATTRIBUTE_RELATION_GROUP';
export const SET_TEMPORARY_ATTRIBUTE =
  'ContentTypeBuilder/App/SET_TEMPORARY_ATTRIBUTE';
export const SET_TEMPORARY_ATTRIBUTE_GROUP =
  'ContentTypeBuilder/App/SET_TEMPORARY_ATTRIBUTE_GROUP';
export const SET_TEMPORARY_ATTRIBUTE_RELATION =
  'ContentTypeBuilder/App/SET_TEMPORARY_ATTRIBUTE_RELATION';
export const SET_TEMPORARY_ATTRIBUTE_RELATION_GROUP =
  'ContentTypeBuilder/App/SET_TEMPORARY_ATTRIBUTE_RELATION_GROUP';
export const SUBMIT_CONTENT_TYPE = 'ContentTypeBuilder/App/SUBMIT_CONTENT_TYPE';
export const SUBMIT_CONTENT_TYPE_SUCCEEDED =
  'ContentTypeBuilder/App/SUBMIT_CONTENT_TYPE_SUCCEEDED';
export const SUBMIT_GROUP = 'ContentTypeBuilder/App/SUBMIT_GROUP';
export const SUBMIT_GROUP_SUCCEEDED =
  'ContentTypeBuilder/App/SUBMIT_GROUP_SUCCEEDED';
export const SUBMIT_TEMP_CONTENT_TYPE =
  'ContentTypeBuilder/App/SUBMIT_TEMP_CONTENT_TYPE';
export const SUBMIT_TEMP_CONTENT_TYPE_SUCCEEDED =
  'ContentTypeBuilder/App/SUBMIT_TEMP_CONTENT_TYPE_SUCCEEDED';
export const SUBMIT_TEMP_GROUP = 'ContentTypeBuilder/App/SUBMIT_TEMP_GROUP';
export const SUBMIT_TEMP_GROUP_SUCCEEDED =
  'ContentTypeBuilder/App/SUBMIT_TEMP_GROUP_SUCCEEDED';
export const UPDATE_TEMP_CONTENT_TYPE =
  'ContentTypeBuilder/App/UPDATE_TEMP_CONTENT_TYPE';
export const UPDATE_TEMP_GROUP = 'ContentTypeBuilder/App/UPDATE_TEMP_GROUP';
