name: Admin bundle-size

on:
  pull_request:
    paths:
      - '**/admin/src/**.js'
      - '**/ee/admin/**.js'
      - '**/translations/**.json'

      # Might be too broad, but it runs the action even if a
      # package.json wasn't changed, e.g. for non-pinned dependencies
      - 'yarn.lock'

jobs:
  admin_size:
    runs-on: ubuntu-latest

    # Allows the action to comment on PRs
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Monorepo build
        uses: ./.github/actions/run-build

      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'build:size'
          pattern: '**/build/**/*.{js,css,html,svg}'
          strip-hash: "-([-\\w]{8})(\\.\\w+)$"
          minimum-change-threshold: '5%'

          # FIXME: exclude unnamed webpack chunks - remove once webpack
          # does not create them anymore
          exclude: '{**/build/**/+([0-9]{,4})*,**/node_modules/**}'
