name: 🐛 Bug Report
description: Report a bug to help us improve this repository.
body:
  - type: input
    id: nodeVersion
    attributes:
      label: Node.js Version
      description: Version of Node.js (only LTS versions are supported).
      placeholder: 20.0.0
    validations:
      required: true

  - type: input
    id: pmVersion
    attributes:
      label: Package Manager Version
      description: Specify your package manager and version (npm, yarn, pnpm, etc.).
      placeholder: npm 10.0.0
    validations:
      required: true

  - type: input
    id: strapiVersion
    attributes:
      label: Strapi Version
      description: Exact Strapi version in use (not “latest”).
      placeholder: 5.7.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Select the OS where the issue occurs.
      options:
        - Strapi Cloud
        - macOS
        - Linux (Debian/Ubuntu)
        - Linux (RedHat/CentOS)
        - Linux (Other)
        - Windows 10
        - Windows 11
        - Docker/Podman/LXC
        - Other
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Database
      description: Select the database you’re using.
      options:
        - Strapi Cloud
        - SQLite
        - MySQL
        - MariaDB
        - PostgreSQL
        - Other
    validations:
      required: true

  - type: dropdown
    id: codeType
    attributes:
      label: Language
      description: Select the language your project uses.
      options:
        - JavaScript
        - TypeScript
        - Other
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Reproduction URL
      description: (Optional) Link to a repository reproducing the issue.
      placeholder: https://github.com/strapi/LaunchPad

  - type: textarea
    id: bugDescription
    attributes:
      label: Bug Description
      description: Describe the issue clearly and concisely.
      placeholder: Example: When fetching data from the REST API, I get a 500 error.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step guide to reproduce the issue.
      placeholder: |
        1. Create a content type with fields: title, content
        2. Add sample data
        3. Fetch data via REST API
        4. Observe the unexpected behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Explain what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Include relevant logs (server or browser console).
      render: shell

  - type: textarea
    id: codeSnippets
    attributes:
      label: Code Snippets
      description: Include related code snippets if applicable.

  - type: textarea
    id: media
    attributes:
      label: Screenshots or Videos
      description: Add screenshots or videos illustrating the issue.

  - type: textarea
    id: additionalInfo
    attributes:
      label: Additional Information
      description: Any other details that might help debug the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmation Checklist
      options:
        - label: I have checked for duplicate [issues](https://github.com/strapi/strapi/issues).
          required: true
        - label: I agree to follow this project’s [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).
          required: true
