// This file is auto-generated by `yarn verify:translations --write-types`.
// Do not edit manually.

import en from './en.json';

export type SentryTradKey = keyof typeof en;

export type SentryMessageId = `sentry.${SentryTradKey}`;
