import path from 'path';
import os from 'os';
import fse from 'fs-extra';
import { type Knex } from 'knex';
import { Database } from '../../index';
import { createMigrationsProvider } from '../index';
import { createUserMigrationProvider } from '../users';
import { renderMigrationFile } from '../file-builder';
import type { MigrationFileOperation } from '../file-builder';

jest.mock('../internal-migrations', () => ({ internalMigrations: [] }));

type DriverName = 'sqlite' | 'postgres' | 'mysql';

interface DriverContext {
  driver: DriverName;
  workDir: string;
  schema?: string;
}

const createLogger = () => ({
  info: jest.fn(),
  warn: jest.fn(),
  error: jest.fn(),
  debug: jest.fn(),
});

type TestLogger = ReturnType<typeof createLogger>;

/**
 * Every fixture is built with the *real* generator (not a hand-written file) so
 * what runs here is exactly what the Content-Type Builder ships: helper calls
 * (`db.schema.renameColumn(knex, …)` etc.) whose guards live in the database
 * package, not in the generated file.
 */
const generate = (operations: MigrationFileOperation[]) =>
  renderMigrationFile({ timestamp: '2026.01.01T00.00.00.000', operations });

const GUARDED_RENAME_MIGRATION = generate([
  { kind: 'renameColumn', table: 'articles', from: 'old_title', to: 'new_title' },
]);

/**
 * Three-step swap migration as generated by the CTB when the user swaps two
 * field names. The CTB forbids duplicate names, so the user necessarily routes
 * through their own intermediate name (`tmp_field`); the migration replays that
 * exact path verbatim — no synthetic temp column is introduced.
 */
const SWAP_RENAME_MIGRATION = generate([
  { kind: 'renameColumn', table: 'articles', from: 'title_a', to: 'tmp_field' },
  { kind: 'renameColumn', table: 'articles', from: 'title_b', to: 'title_a' },
  { kind: 'renameColumn', table: 'articles', from: 'tmp_field', to: 'title_b' },
]);

const GUARDED_PRIMITIVES_MIGRATION = generate([
  { kind: 'renameColumn', table: 'articles', from: 'old_title', to: 'new_title' },
  { kind: 'renameTable', from: 'old_articles_tags_links', to: 'new_articles_tags_links' },
  {
    kind: 'updateRows',
    table: 'articles_cmps',
    where: { component_type: 'default.old-box' },
    set: { component_type: 'default.new-box' },
  },
]);

const GUARDED_RENAME_TABLE_MIGRATION = generate([
  { kind: 'renameTable', from: 'old_articles_tags_links', to: 'new_articles_tags_links' },
]);

const GUARDED_UPDATE_ROWS_MIGRATION = generate([
  {
    kind: 'updateRows',
    table: 'articles_cmps',
    where: { component_type: 'default.old-box' },
    set: { component_type: 'default.new-box' },
  },
]);

const RENAME_LINK_TABLE_MIGRATION = generate([
  { kind: 'renameTable', from: 'articles_a_lnk', to: 'articles_b_lnk' },
]);

const RENAME_FK_COLUMN_MIGRATION = generate([
  { kind: 'renameColumn', table: 'components', from: 'old_ref', to: 'new_ref' },
]);

const GUARDED_ORDER_MARKER_MIGRATION = `module.exports = {
  async up(knex) {
    if (await knex.schema.hasTable('internal_order_markers')) {
      await knex('internal_order_markers').insert({ name: 'user-ran-after-internal' });
    }
  },
  async down() {},
};
`;

const createDatabase = (
  { driver, workDir, schema }: DriverContext,
  logger: TestLogger
): Database => {
  if (driver === 'postgres') {
    return new Database({
      logger,
      connection: {
        client: 'postgres',
        // `schema` isolates parallel pg test runs; it is not part of knex's
        // connection typings, so assert the shape.
        connection: {
          host: '127.0.0.1',
          port: 5432,
          database: 'strapi_test',
          user: 'strapi',
          password: 'strapi',
          schema,
        } as Knex.PgConnectionConfig,
        pool: { min: 0, max: 1 },
        acquireConnectionTimeout: 1000,
      },
      settings: {
        migrations: { dir: path.join(workDir, 'migrations') },
        runMigrations: true,
        forceMigration: true,
      },
    });
  }

  if (driver === 'mysql') {
    return new Database({
      logger,
      connection: {
        client: 'mysql',
        connection: {
          host: '127.0.0.1',
          port: 3306,
          database: 'strapi_test',
          user: 'strapi',
          password: 'strapi',
        },
        pool: { min: 0, max: 1 },
        acquireConnectionTimeout: 1000,
      },
      settings: {
        migrations: { dir: path.join(workDir, 'migrations') },
        runMigrations: true,
        forceMigration: true,
      },
    });
  }

  return new Database({
    logger,
    connection: {
      client: 'sqlite',
      connection: { filename: path.join(workDir, 'test.db') },
      useNullAsDefault: true,
      pool: { min: 0, max: 1 },
    },
    settings: {
      migrations: { dir: path.join(workDir, 'migrations') },
      runMigrations: true,
      forceMigration: true,
    },
  });
};

const writeMigration = (workDir: string, name: string, content: string) => {
  const dir = path.join(workDir, 'migrations');
  fse.ensureDirSync(dir);
  fse.writeFileSync(path.join(dir, name), content, 'utf8');
};

const getExecutedMigrations = async (db: Database): Promise<string[]> => {
  const rows = await db.connection('strapi_migrations').select('name');
  return rows.map((row: { name: string }) => row.name);
};

const getExecutedInternalMigrations = async (db: Database): Promise<string[]> => {
  const rows = await db.connection('strapi_migrations_internal').select('name');
  return rows.map((row: { name: string }) => row.name);
};

const resetMysqlTables = async (db: Database) => {
  await db.connection.raw('SET FOREIGN_KEY_CHECKS = 0');
  for (const table of [
    'strapi_migrations',
    'strapi_migrations_internal',
    'articles',
    'old_articles_tags_links',
    'new_articles_tags_links',
    'articles_cmps',
    'internal_order_markers',
    'articles_a_lnk',
    'articles_b_lnk',
    'components',
  ]) {
    await db.connection.schema.dropTableIfExists(table);
  }
  await db.connection.raw('SET FOREIGN_KEY_CHECKS = 1');
};

const prepareDatabase = async (db: Database, context: DriverContext) => {
  if (context.driver === 'postgres' && context.schema) {
    await db.connection.raw(`CREATE SCHEMA IF NOT EXISTS "${context.schema}"`);
  }

  if (context.driver === 'mysql') {
    await resetMysqlTables(db);
  }
};

const cleanupDatabase = async (db: Database, context: DriverContext) => {
  if (context.driver === 'postgres' && context.schema) {
    await db.connection.raw(`DROP SCHEMA IF EXISTS "${context.schema}" CASCADE`);
  }

  if (context.driver === 'mysql') {
    await resetMysqlTables(db);
  }
};

const connectOrSkip = async (
  context: DriverContext,
  logger: TestLogger
): Promise<Database | null> => {
  const db = createDatabase(context, logger);

  try {
    await db.connection.raw('SELECT 1');
    await prepareDatabase(db, context);
    return db;
  } catch (error) {
    await db.destroy();

    if (context.driver !== 'sqlite') {
      const cause = error instanceof Error ? error.message : String(error);
      // eslint-disable-next-line no-console
      console.warn(`Skipping ${context.driver} fresh-DB rename migration tests: ${cause}`);
      return null;
    }

    throw error;
  }
};

const drivers: DriverName[] = ['sqlite', 'postgres', 'mysql'];

describe.each(drivers)(
  'user migration runner — guarded rename on a fresh %s database',
  (driver) => {
    let workDir: string;
    let db: Database | null;
    let context: DriverContext;
    let logger: TestLogger;

    beforeEach(async () => {
      logger = createLogger();
      workDir = fse.mkdtempSync(path.join(os.tmpdir(), 'ctb-freshdb-'));
      context = {
        driver,
        workDir,
        schema:
          driver === 'postgres'
            ? `ctb_freshdb_${Date.now()}_${Math.random().toString(36).slice(2)}`
            : undefined,
      };
      db = await connectOrSkip(context, logger);
    });

    afterEach(async () => {
      if (db) {
        await cleanupDatabase(db, context);
        await db.destroy();
      }
      fse.removeSync(workDir);
    });

    it('records guarded no-op primitives as executed on a fresh (empty) DB', async () => {
      if (!db) {
        return;
      }

      writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', GUARDED_PRIMITIVES_MIGRATION);

      const provider = createUserMigrationProvider(db);

      expect(await provider.shouldRun()).toBe(true);

      // Must not throw even though the target tables/columns do not exist yet.
      await expect(provider.up()).resolves.not.toThrow();

      const executed = await getExecutedMigrations(db);
      expect(executed).toContain('2026.01.01.00.00.00.rename-fields.js');

      // A clean deploy must not spam warnings: skipped steps whose source does
      // not exist yet are logged at info level only.
      expect(logger.warn).not.toHaveBeenCalled();
      expect(logger.info).toHaveBeenCalledWith(
        expect.stringContaining('[rename migration] skipped')
      );
    });

    it('does not re-run (and therefore cannot double-rename) once recorded', async () => {
      if (!db) {
        return;
      }

      writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', GUARDED_RENAME_MIGRATION);

      const provider = createUserMigrationProvider(db);

      // First boot: fresh DB, guarded no-op, recorded as executed.
      await provider.up();
      expect(await provider.shouldRun()).toBe(false);

      // Simulate schema-sync creating the table afterwards with the *new* column.
      await db.connection.schema.createTable('articles', (table) => {
        table.increments('id');
        table.string('new_title');
      });

      // Second boot: migration is already recorded, so it must not run again and
      // must not wrongly rename the freshly-created `new_title` column.
      expect(await provider.shouldRun()).toBe(false);
      await provider.up();

      expect(await db.connection.schema.hasColumn('articles', 'new_title')).toBe(true);
      expect(await db.connection.schema.hasColumn('articles', 'old_title')).toBe(false);
    });

    it('renames the column (preserving data) when the old column exists', async () => {
      if (!db) {
        return;
      }

      writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', GUARDED_RENAME_MIGRATION);

      // Seed an existing table with data under the old column name.
      await db.connection.schema.createTable('articles', (table) => {
        table.increments('id');
        table.string('old_title');
      });
      await db.connection('articles').insert({ old_title: 'Hello' });

      const provider = createUserMigrationProvider(db);
      await provider.up();

      expect(await db.connection.schema.hasColumn('articles', 'new_title')).toBe(true);
      expect(await db.connection.schema.hasColumn('articles', 'old_title')).toBe(false);

      const rows = await db.connection('articles').select('new_title');
      expect(rows).toEqual([{ new_title: 'Hello' }]);

      const executed = await getExecutedMigrations(db);
      expect(executed).toContain('2026.01.01.00.00.00.rename-fields.js');
      expect(logger.warn).not.toHaveBeenCalled();
    });

    it('is a no-op (does not throw) when the target column already exists', async () => {
      if (!db) {
        return;
      }

      // Deploy scenario: an earlier save already produced a column with the new
      // name (e.g. delete `new_title`, then rename `old_title -> new_title` in a
      // later save). Both migrations ship together, and this one runs before
      // schema-sync, so `new_title` still physically exists. The rename must be a
      // guarded no-op rather than throwing a duplicate-column error that would
      // fail the migration transaction and stop the app from booting.
      writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', GUARDED_RENAME_MIGRATION);

      await db.connection.schema.createTable('articles', (table) => {
        table.increments('id');
        table.string('old_title');
        table.string('new_title');
      });
      await db.connection('articles').insert({ old_title: 'Old', new_title: 'New' });

      const provider = createUserMigrationProvider(db);

      await expect(provider.up()).resolves.not.toThrow();

      // Unlike the fresh-database case this is a drifted environment: the skip
      // is surfaced as a warning so it does not go unnoticed.
      expect(logger.warn).toHaveBeenCalledWith(
        expect.stringContaining(
          '[rename migration] skipped: Rename column articles.old_title to new_title (column "articles.new_title" already exists)'
        )
      );

      // Both columns remain; no rename happened and no data was clobbered.
      expect(await db.connection.schema.hasColumn('articles', 'old_title')).toBe(true);
      expect(await db.connection.schema.hasColumn('articles', 'new_title')).toBe(true);

      const rows = await db.connection('articles').select('old_title', 'new_title');
      expect(rows).toEqual([{ old_title: 'Old', new_title: 'New' }]);

      const executed = await getExecutedMigrations(db);
      expect(executed).toContain('2026.01.01.00.00.00.rename-fields.js');
    });

    it('swaps two columns (preserving both values) when a cyclic rename migration runs', async () => {
      if (!db) {
        return;
      }

      writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', SWAP_RENAME_MIGRATION);

      await db.connection.schema.createTable('articles', (table) => {
        table.increments('id');
        table.string('title_a');
        table.string('title_b');
      });
      await db.connection('articles').insert({ title_a: 'Value A', title_b: 'Value B' });

      const provider = createUserMigrationProvider(db);
      await provider.up();

      expect(await db.connection.schema.hasColumn('articles', 'title_a')).toBe(true);
      expect(await db.connection.schema.hasColumn('articles', 'title_b')).toBe(true);
      expect(await db.connection.schema.hasColumn('articles', 'tmp_field')).toBe(false);

      const rows = await db.connection('articles').select('title_a', 'title_b');
      expect(rows).toEqual([{ title_a: 'Value B', title_b: 'Value A' }]);
    });

    it('renames a table (preserving rows) when the old table exists', async () => {
      if (!db) {
        return;
      }

      writeMigration(
        workDir,
        '2026.01.01.00.00.00.rename-fields.js',
        GUARDED_RENAME_TABLE_MIGRATION
      );

      await db.connection.schema.createTable('old_articles_tags_links', (table) => {
        table.increments('id');
        table.integer('article_id');
      });
      await db.connection('old_articles_tags_links').insert({ article_id: 12 });

      const provider = createUserMigrationProvider(db);
      await provider.up();

      expect(await db.connection.schema.hasTable('new_articles_tags_links')).toBe(true);
      expect(await db.connection.schema.hasTable('old_articles_tags_links')).toBe(false);

      const rows = await db.connection('new_articles_tags_links').select('article_id');
      expect(rows).toEqual([{ article_id: 12 }]);
    });

    it('updates guarded rows when the target table and guard column exist', async () => {
      if (!db) {
        return;
      }

      writeMigration(
        workDir,
        '2026.01.01.00.00.00.rename-fields.js',
        GUARDED_UPDATE_ROWS_MIGRATION
      );

      await db.connection.schema.createTable('articles_cmps', (table) => {
        table.increments('id');
        table.string('component_type');
        table.string('field');
      });
      await db.connection('articles_cmps').insert([
        { component_type: 'default.old-box', field: 'zone' },
        { component_type: 'default.other-box', field: 'zone' },
      ]);

      const provider = createUserMigrationProvider(db);
      await provider.up();

      const rows = await db.connection('articles_cmps').select('component_type').orderBy('id');
      expect(rows).toEqual([
        { component_type: 'default.new-box' },
        { component_type: 'default.other-box' },
      ]);
    });

    it('runs guarded user migrations before registered internal migrations on a fresh DB', async () => {
      if (!db) {
        return;
      }

      writeMigration(
        workDir,
        '2026.01.01.00.00.00.order-marker.js',
        GUARDED_ORDER_MARKER_MIGRATION
      );

      const provider = createMigrationsProvider(db);
      await provider.providers.internal.register({
        name: '2026.01.01.00.00.01-internal-order-marker',
        async up(knex) {
          await knex.schema.createTable('internal_order_markers', (table) => {
            table.increments('id');
            table.string('name');
          });
          await knex('internal_order_markers').insert({ name: 'internal-ran' });
        },
        async down() {
          /* no-op */
        },
      });

      await expect(provider.up()).resolves.not.toThrow();

      const rows = await db.connection('internal_order_markers').select('name');
      expect(rows).toEqual([{ name: 'internal-ran' }]);

      expect(await getExecutedMigrations(db)).toContain('2026.01.01.00.00.00.order-marker.js');
      expect(await getExecutedInternalMigrations(db)).toContain(
        '2026.01.01.00.00.01-internal-order-marker'
      );

      expect(await provider.shouldRun()).toBe(false);
      await provider.up();
      expect(await db.connection('internal_order_markers').select('name')).toEqual([
        { name: 'internal-ran' },
      ]);
    });

    /**
     * Mirrors a Strapi join table: a named FK constraint and a same-named index
     * on the FK column (see `metadata/relations.ts` and `schema/schema.ts`).
     */
    const createLinkTable = async (name: string, fkName: string) => {
      await db!.connection.schema.createTable(name, (table) => {
        table.increments('id');
        table.integer('article_id').unsigned();
        table.index(['article_id'], fkName);
        table
          .foreign('article_id', fkName)
          .references('id')
          .inTable('articles')
          .onDelete('CASCADE');
      });
    };

    const listSchemaObjectNames = async (table: string) => {
      const indexes = await db!.dialect.schemaInspector.getIndexes(table);
      const foreignKeys = await db!.dialect.schemaInspector.getForeignKeys(table);
      return [...indexes, ...foreignKeys].map((object) => object.name);
    };

    it('leaves no index named after a renamed table, so the old name can be re-created', async () => {
      if (!db) {
        return;
      }

      const { identifiers } = db.metadata;
      const oldFk = identifiers.getFkIndexName('articles_a_lnk');
      const newFk = identifiers.getFkIndexName('articles_b_lnk');

      writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', RENAME_LINK_TABLE_MIGRATION);

      await db.connection.schema.createTable('articles', (table) => {
        table.increments('id');
      });
      await createLinkTable('articles_a_lnk', oldFk);

      await createUserMigrationProvider(db).up();

      expect(await db.connection.schema.hasTable('articles_b_lnk')).toBe(true);
      const names = await listSchemaObjectNames('articles_b_lnk');
      expect(names.filter((name) => name.startsWith('articles_a_lnk'))).toEqual([]);
      if (db.dialect.canRenameSchemaObjects()) {
        // Postgres renames both the FK constraint and its same-named index.
        expect(names).toEqual(expect.arrayContaining([newFk]));
      }

      // What schema sync does next when the same save re-adds the old name
      // (rename `a -> b`, add a new `a`): must not collide.
      await expect(createLinkTable('articles_a_lnk', oldFk)).resolves.not.toThrow();
    });

    it('leaves no index named after a renamed column, so the old name can be re-created', async () => {
      if (!db) {
        return;
      }

      const { identifiers } = db.metadata;
      const oldFk = identifiers.getFkIndexName(['components', 'old_ref']);
      const newFk = identifiers.getFkIndexName(['components', 'new_ref']);

      writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', RENAME_FK_COLUMN_MIGRATION);

      await db.connection.schema.createTable('articles', (table) => {
        table.increments('id');
      });
      await db.connection.schema.createTable('components', (table) => {
        table.increments('id');
        table.integer('old_ref').unsigned();
        table.index(['old_ref'], oldFk);
        table.foreign('old_ref', oldFk).references('id').inTable('articles').onDelete('SET NULL');
      });

      await createUserMigrationProvider(db).up();

      expect(await db.connection.schema.hasColumn('components', 'new_ref')).toBe(true);
      const names = await listSchemaObjectNames('components');
      expect(names).not.toContain(oldFk);
      if (db.dialect.canRenameSchemaObjects()) {
        expect(names).toEqual(expect.arrayContaining([newFk]));
      }

      await expect(
        db.connection.schema.alterTable('components', (table) => {
          table.integer('old_ref').unsigned();
          table.index(['old_ref'], oldFk);
        })
      ).resolves.not.toThrow();
    });
  }
);
