import path from 'path';
import os from 'os';
import fse from 'fs-extra';

import { Database } from '../../index';
import { createUserMigrationProvider } from '../users';

/**
 * Mirrors the shape of the migration the Content-Type Builder generates for an
 * attribute rename: a guarded `renameColumn` that becomes a safe no-op when the
 * table/column does not exist yet (e.g. on a fresh database, before schema-sync
 * has created the tables).
 */
const GUARDED_RENAME_MIGRATION = `module.exports = {
  async up(knex) {
    if (await knex.schema.hasColumn('articles', 'old_title')) {
      await knex.schema.alterTable('articles', (table) => {
        table.renameColumn('old_title', 'new_title');
      });
    }
  },
  async down() {},
};
`;

/**
 * Three-step swap migration as generated by the CTB when the user swaps two
 * field names. The CTB forbids duplicate names, so the user necessarily routes
 * through their own intermediate name (`tmp_field`); the migration replays that
 * exact path verbatim — no synthetic temp column is introduced.
 */
const SWAP_RENAME_MIGRATION = `module.exports = {
  async up(knex) {
    if (await knex.schema.hasColumn('articles', 'title_a')) {
      await knex.schema.alterTable('articles', (table) => {
        table.renameColumn('title_a', 'tmp_field');
      });
    }
    if (await knex.schema.hasColumn('articles', 'title_b')) {
      await knex.schema.alterTable('articles', (table) => {
        table.renameColumn('title_b', 'title_a');
      });
    }
    if (await knex.schema.hasColumn('articles', 'tmp_field')) {
      await knex.schema.alterTable('articles', (table) => {
        table.renameColumn('tmp_field', 'title_b');
      });
    }
  },
  async down() {},
};
`;

const createSqliteDatabase = (workDir: string): Database => {
  return new Database({
    connection: {
      client: 'sqlite',
      connection: { filename: path.join(workDir, 'test.db') },
      useNullAsDefault: true,
      pool: { min: 0, max: 1 },
    },
    settings: {
      migrations: { dir: path.join(workDir, 'migrations') },
      runMigrations: true,
      forceMigration: true,
    },
  });
};

const writeMigration = (workDir: string, name: string, content: string) => {
  const dir = path.join(workDir, 'migrations');
  fse.ensureDirSync(dir);
  fse.writeFileSync(path.join(dir, name), content, 'utf8');
};

const getExecutedMigrations = async (db: Database): Promise<string[]> => {
  const rows = await db.connection('strapi_migrations').select('name');
  return rows.map((row: { name: string }) => row.name);
};

describe('user migration runner — guarded rename on a fresh database', () => {
  let workDir: string;
  let db: Database;

  beforeEach(() => {
    workDir = fse.mkdtempSync(path.join(os.tmpdir(), 'ctb-freshdb-'));
  });

  afterEach(async () => {
    if (db) {
      await db.destroy();
    }
    fse.removeSync(workDir);
  });

  it('records a guarded no-op migration as executed on a fresh (empty) DB', async () => {
    writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', GUARDED_RENAME_MIGRATION);

    db = createSqliteDatabase(workDir);
    const provider = createUserMigrationProvider(db);

    expect(await provider.shouldRun()).toBe(true);

    // Must not throw even though `articles` does not exist on the fresh DB.
    await expect(provider.up()).resolves.not.toThrow();

    const executed = await getExecutedMigrations(db);
    expect(executed).toContain('2026.01.01.00.00.00.rename-fields.js');
  });

  it('does not re-run (and therefore cannot double-rename) once recorded', async () => {
    writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', GUARDED_RENAME_MIGRATION);

    db = createSqliteDatabase(workDir);
    const provider = createUserMigrationProvider(db);

    // First boot: fresh DB, guarded no-op, recorded as executed.
    await provider.up();
    expect(await provider.shouldRun()).toBe(false);

    // Simulate schema-sync creating the table afterwards with the *new* column.
    await db.connection.schema.createTable('articles', (table) => {
      table.increments('id');
      table.string('new_title');
    });

    // Second boot: migration is already recorded, so it must not run again and
    // must not wrongly rename the freshly-created `new_title` column.
    expect(await provider.shouldRun()).toBe(false);
    await provider.up();

    expect(await db.connection.schema.hasColumn('articles', 'new_title')).toBe(true);
    expect(await db.connection.schema.hasColumn('articles', 'old_title')).toBe(false);
  });

  it('renames the column (preserving data) when the old column exists', async () => {
    writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', GUARDED_RENAME_MIGRATION);

    db = createSqliteDatabase(workDir);

    // Seed an existing table with data under the old column name.
    await db.connection.schema.createTable('articles', (table) => {
      table.increments('id');
      table.string('old_title');
    });
    await db.connection('articles').insert({ old_title: 'Hello' });

    const provider = createUserMigrationProvider(db);
    await provider.up();

    expect(await db.connection.schema.hasColumn('articles', 'new_title')).toBe(true);
    expect(await db.connection.schema.hasColumn('articles', 'old_title')).toBe(false);

    const rows = await db.connection('articles').select('new_title');
    expect(rows).toEqual([{ new_title: 'Hello' }]);

    const executed = await getExecutedMigrations(db);
    expect(executed).toContain('2026.01.01.00.00.00.rename-fields.js');
  });

  it('swaps two columns (preserving both values) when a cyclic rename migration runs', async () => {
    writeMigration(workDir, '2026.01.01.00.00.00.rename-fields.js', SWAP_RENAME_MIGRATION);

    db = createSqliteDatabase(workDir);

    await db.connection.schema.createTable('articles', (table) => {
      table.increments('id');
      table.string('title_a');
      table.string('title_b');
    });
    await db.connection('articles').insert({ title_a: 'Value A', title_b: 'Value B' });

    const provider = createUserMigrationProvider(db);
    await provider.up();

    expect(await db.connection.schema.hasColumn('articles', 'title_a')).toBe(true);
    expect(await db.connection.schema.hasColumn('articles', 'title_b')).toBe(true);
    expect(await db.connection.schema.hasColumn('articles', 'tmp_field')).toBe(false);

    const rows = await db.connection('articles').select('title_a', 'title_b');
    expect(rows).toEqual([{ title_a: 'Value B', title_b: 'Value A' }]);
  });
});
