name: 'Run e2e tests'
description: 'Run e2e tests'
inputs:
  runEE:
    description: 'Should run EE or CE e2e tests'
  jestOptions:
    description: 'Jest options'
  enableFutureFeatures:
    description: 'Enable future unstable features'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      env:
        RUN_EE: ${{ inputs.runEE }}
        JEST_OPTIONS: ${{ inputs.jestOptions }}
        STRAPI_FEATURES_FUTURE_RELEASES_SCHEDULING: ${{ inputs.enableFutureFeatures }}
      shell: bash
