import path from 'node:path';
import fse from 'fs-extra';

import type { Database } from '..';

export interface BuiltMigrationFile {
  filename: string;
  content: string;
}

export interface RenameColumnOperation {
  table: string;
  from: string;
  to: string;
  comment?: string;
}

export interface RenameTableOperation {
  from: string;
  to: string;
  comment?: string;
}

export interface UpdateRowsOperation {
  table: string;
  where: Record<string, string>;
  set: Record<string, string>;
  guardColumn?: string;
  comment?: string;
}

/**
 * One logical operation per generated file: the composed `origin -> final`
 * attribute renames of every model that received hops, keyed by model uid.
 * Dispatched at runtime to the handlers registered on `db.schema` (e.g. admin
 * field permissions); the database package itself stores nothing by attribute
 * name.
 */
export interface AttributeRenamesOperation {
  renames: Record<string, Record<string, string>>;
  comment?: string;
}

export type MigrationFileOperation =
  | ({ kind: 'renameColumn' } & RenameColumnOperation)
  | ({ kind: 'renameTable' } & RenameTableOperation)
  | ({ kind: 'updateRows' } & UpdateRowsOperation)
  | ({ kind: 'attributeRenames' } & AttributeRenamesOperation);

export type MigrationFileFormat = 'javascript' | 'typescript';

const FILE_EXTENSIONS: Record<MigrationFileFormat, string> = {
  javascript: 'js',
  typescript: 'ts',
};

/**
 * Produces a sortable, filesystem-safe UTC timestamp (e.g. `2026.06.11T15.16.00.123`).
 *
 * Based on the migration generator's format but keeps milliseconds: generated
 * migrations can be written multiple times in the same second, so second
 * precision would produce colliding filenames. UTC (not local time) so that
 * files generated by developers in different time zones still sort in the
 * order they were created.
 */
export const getFormattedTimestamp = (date: Date = new Date()): string => {
  return date.toJSON().replace(/[-:]/g, '.').replace(/Z$/, '');
};

const HEADER_COMMENT = `/**
 * Auto-generated by Strapi on {{timestamp}}.
 *
 * Every step goes through the database rename helpers, which check that the
 * source table/column exists and the target does not before touching anything,
 * so this file is a safe no-op on a fresh database (the tables are created by
 * schema sync afterwards). Skipped steps are logged at startup.
 */`;

const JS_TEMPLATE = `'use strict';

${HEADER_COMMENT}
module.exports = {
  async up(knex, db) {
{{body}}
  },
  async down(knex, db) {
    // Down migrations are not generated for automatically generated migrations.
  },
};
`;

const TS_TEMPLATE = `import type { Knex } from 'knex';
import type { Core } from '@strapi/strapi';

${HEADER_COMMENT}
export default {
  async up(knex: Knex, db: Core.Strapi['db']) {
{{body}}
  },
  async down(knex: Knex, db: Core.Strapi['db']) {
    // Down migrations are not generated for automatically generated migrations.
  },
};
`;

const TEMPLATES: Record<MigrationFileFormat, string> = {
  javascript: JS_TEMPLATE,
  typescript: TS_TEMPLATE,
};

const RENAME_COLUMN_SNIPPET = `    // {{comment}}
    await db.schema.renameColumn(knex, { table: {{table}}, from: {{from}}, to: {{to}} });`;

const RENAME_TABLE_SNIPPET = `    // {{comment}}
    await db.schema.renameTable(knex, { from: {{from}}, to: {{to}} });`;

const UPDATE_ROWS_SNIPPET = `    // {{comment}}
    await db.schema.updateRows(knex, {
      table: {{table}},
      guardColumn: {{guardColumn}},
      where: {{where}},
      set: {{set}},
    });`;

const ATTRIBUTE_RENAMES_SNIPPET = `    // {{comment}}
    await db.schema.applyAttributeRenames(knex, {
      renames: {{renames}},
    });`;

const interpolate = (template: string, values: Record<string, string>): string => {
  return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_match, key: string) => {
    return key in values ? values[key] : `{{${key}}}`;
  });
};

const quote = (value: string): string =>
  `'${value
    .replaceAll('\\', String.raw`\\`)
    .replaceAll("'", String.raw`\'`)
    .replaceAll('\r', String.raw`\r`)
    .replaceAll('\n', String.raw`\n`)
    .replaceAll('\u2028', String.raw`\u2028`)
    .replaceAll('\u2029', String.raw`\u2029`)}'`;

const IDENTIFIER_KEY = /^[A-Za-z_$][\w$]*$/;

const renderKey = (key: string): string => (IDENTIFIER_KEY.test(key) ? key : quote(key));

const renderObject = (values: Record<string, string>): string => {
  return `{ ${Object.entries(values)
    .map(([key, value]) => `${renderKey(key)}: ${quote(value)}`)
    .join(', ')} }`;
};

/**
 * Renders `{ uid: { from: to } }` one entry per line, every key and value
 * quoted (uids contain `:` and `.`).
 */
const renderNestedObject = (values: Record<string, Record<string, string>>): string => {
  const lines = Object.entries(values).map(([key, inner]) => {
    const entries = Object.entries(inner)
      .map(([from, to]) => `${quote(from)}: ${quote(to)}`)
      .join(', ');
    return `        ${quote(key)}: { ${entries} },`;
  });

  if (lines.length === 0) {
    return '{}';
  }

  return `{\n${lines.join('\n')}\n      }`;
};

/**
 * Comments are rendered after `//`; a line break (including the JS line
 * separators U+2028 / U+2029) would end the comment and let the rest run as
 * code, so every comment is flattened to a single line.
 */
const sanitizeComment = (comment: string): string => comment.replace(/[\r\n\u2028\u2029]/g, ' ');

const getDefaultOperationComment = (op: MigrationFileOperation): string => {
  switch (op.kind) {
    case 'attributeRenames':
      return "Update stores keyed by attribute name (admin field permissions) for this save's renames";
    case 'renameTable':
      return `Rename table ${op.from} to ${op.to}`;
    case 'updateRows':
      return `Update rows in ${op.table}`;
    case 'renameColumn':
    default:
      return `Rename column ${op.table}.${op.from} to ${op.to}`;
  }
};

export const getOperationComment = (op: MigrationFileOperation): string => {
  return sanitizeComment(op.comment || getDefaultOperationComment(op));
};

export const renderMigrationFileOperation = (op: MigrationFileOperation): string => {
  const comment = getOperationComment(op);

  switch (op.kind) {
    case 'attributeRenames':
      return interpolate(ATTRIBUTE_RENAMES_SNIPPET, {
        comment,
        renames: renderNestedObject(op.renames),
      });
    case 'renameTable':
      return interpolate(RENAME_TABLE_SNIPPET, {
        comment,
        from: quote(op.from),
        to: quote(op.to),
      });
    case 'updateRows': {
      const [firstSetColumn] = Object.keys(op.set);
      return interpolate(UPDATE_ROWS_SNIPPET, {
        comment,
        table: quote(op.table),
        guardColumn: quote(op.guardColumn ?? firstSetColumn),
        where: renderObject(op.where),
        set: renderObject(op.set),
      });
    }
    case 'renameColumn':
    default:
      return interpolate(RENAME_COLUMN_SNIPPET, {
        comment,
        table: quote(op.table),
        from: quote(op.from),
        to: quote(op.to),
      });
  }
};

export const renderMigrationFile = ({
  timestamp,
  operations,
  format = 'javascript',
}: {
  timestamp: string;
  operations: MigrationFileOperation[];
  format?: MigrationFileFormat;
}): string => {
  const body = operations.map(renderMigrationFileOperation).join('\n\n');
  return interpolate(TEMPLATES[format], { timestamp, body });
};

interface BuildOptions {
  name: string;
  /**
   * Module format of the generated file. `typescript` emits an ES module with
   * typed `up`/`down` signatures and a `.ts` extension so the app's `tsc` build
   * compiles it into `dist/database/migrations`, which is where migrations are
   * discovered when `useTypescriptMigrations` is enabled. Defaults to
   * `javascript` (CommonJS).
   */
  format?: MigrationFileFormat;
}

interface WriteOptions extends BuildOptions {
  /**
   * Directory the migration file is written to. Defaults to the database's
   * configured migrations directory. The Content-Type Builder passes the app's
   * source `database/migrations` explicitly so the file is never written into
   * build output (e.g. `dist/` when `useTypescriptMigrations` is enabled).
   */
  dir?: string;
}

const MAX_WRITE_ATTEMPTS = 1000;

interface MigrationFileBuilderDeps {
  db: Database;
}

export const createMigrationFileBuilder = ({ db }: MigrationFileBuilderDeps) => {
  const operations: MigrationFileOperation[] = [];

  const resolveMigrationsDir = (): string => {
    return (
      db.config?.settings?.migrations?.dir ?? path.join(process.cwd(), 'database', 'migrations')
    );
  };

  return {
    renameColumn(op: RenameColumnOperation): void {
      operations.push({ kind: 'renameColumn', ...op });
    },

    renameTable(op: RenameTableOperation): void {
      operations.push({ kind: 'renameTable', ...op });
    },

    updateRows(op: UpdateRowsOperation): void {
      operations.push({ kind: 'updateRows', ...op });
    },

    attributeRenames(op: AttributeRenamesOperation): void {
      operations.push({ kind: 'attributeRenames', ...op });
    },

    hasChanges(): boolean {
      return operations.length > 0;
    },

    getOperations(): MigrationFileOperation[] {
      return [...operations];
    },

    build(
      { name, format = 'javascript' }: BuildOptions,
      date: Date = new Date()
    ): BuiltMigrationFile | null {
      if (operations.length === 0) {
        return null;
      }

      const timestamp = getFormattedTimestamp(date);
      const content = renderMigrationFile({ timestamp, operations, format });
      const filename = `${timestamp}.${name}.${FILE_EXTENSIONS[format]}`;

      return { filename, content };
    },

    async writeFiles(options: WriteOptions): Promise<string | null> {
      const dir = options.dir ?? resolveMigrationsDir();
      const start = Date.now();

      // On a collision, bump the timestamp by 1ms (filename and header) rather
      // than suffixing the name: `…000.name-1.js` would sort before
      // `…000.name.js` and run first.
      for (let attempt = 0; attempt < MAX_WRITE_ATTEMPTS; attempt += 1) {
        const built = this.build(options, new Date(start + attempt));
        if (!built) {
          return null;
        }

        if (attempt === 0) {
          await fse.ensureDir(dir);
        }

        const filePath = path.join(dir, built.filename);
        if (await fse.pathExists(filePath)) {
          continue;
        }

        await fse.writeFile(filePath, built.content, 'utf8');
        return filePath;
      }

      throw new Error(
        `Could not find a free migration filename in "${dir}" after ${MAX_WRITE_ATTEMPTS} attempts`
      );
    },
  };
};

export type MigrationFileBuilder = ReturnType<typeof createMigrationFileBuilder>;
