import path from 'node:path';
import fse from 'fs-extra';

import type { Database } from '..';

export interface BuiltMigrationFile {
  filename: string;
  content: string;
}

export interface RenameColumnOperation {
  table: string;
  from: string;
  to: string;
  comment?: string;
}

export interface RenameTableOperation {
  from: string;
  to: string;
  comment?: string;
}

export interface UpdateRowsOperation {
  table: string;
  where: Record<string, string>;
  set: Record<string, string>;
  guardColumn?: string;
  comment?: string;
}

export type MigrationFileOperation =
  | ({ kind: 'renameColumn' } & RenameColumnOperation)
  | ({ kind: 'renameTable' } & RenameTableOperation)
  | ({ kind: 'updateRows' } & UpdateRowsOperation);

/**
 * Produces a sortable, filesystem-safe timestamp (e.g. `2026.06.11T15.16.00.123`).
 *
 * Based on the migration generator's format but keeps milliseconds: generated
 * migrations can be written multiple times in the same second, so second
 * precision would produce colliding filenames.
 */
const getFormattedTimestamp = (date: Date = new Date()): string => {
  return new Date(date.getTime() - date.getTimezoneOffset() * 60000)
    .toJSON()
    .replace(/[-:]/g, '.')
    .replace(/Z$/, '');
};

const JS_TEMPLATE = `'use strict';

/**
 * Auto-generated by Strapi on {{timestamp}}.
 *
 * Guarded so it is a safe no-op on a fresh database where the target tables or
 * columns do not exist yet.
 */
module.exports = {
  async up(knex) {
{{body}}
  },
  async down(knex) {
    // Down migrations are not generated for automatically generated migrations.
  },
};
`;

const RENAME_COLUMN_SNIPPET = `    // {{comment}}
    if (
      (await knex.schema.hasTable({{table}})) &&
      (await knex.schema.hasColumn({{table}}, {{from}}))
    ) {
      await knex.schema.alterTable({{table}}, (table) => {
        table.renameColumn({{from}}, {{to}});
      });
    }`;

const RENAME_TABLE_SNIPPET = `    // {{comment}}
    if (
      (await knex.schema.hasTable({{from}})) &&
      !(await knex.schema.hasTable({{to}}))
    ) {
      await knex.schema.renameTable({{from}}, {{to}});
    }`;

const UPDATE_ROWS_SNIPPET = `    // {{comment}}
    if (
      (await knex.schema.hasTable({{table}})) &&
      (await knex.schema.hasColumn({{table}}, {{guardColumn}}))
    ) {
      await knex({{table}}){{where}}.update({{set}});
    }`;

const interpolate = (template: string, values: Record<string, string>): string => {
  return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_match, key: string) => {
    return key in values ? values[key] : `{{${key}}}`;
  });
};

const quote = (value: string): string => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const renderObject = (values: Record<string, string>): string => {
  const entries = Object.entries(values);
  if (entries.length === 1) {
    const [[key, value]] = entries;
    return `${quote(key)}, ${quote(value)}`;
  }

  return `{ ${entries.map(([key, value]) => `${quote(key)}: ${quote(value)}`).join(', ')} }`;
};

const renderWhere = (where: Record<string, string>): string => {
  return Object.entries(where)
    .map(([key, value]) => `.where(${quote(key)}, ${quote(value)})`)
    .join('');
};

export const renderMigrationFileOperation = (op: MigrationFileOperation): string => {
  switch (op.kind) {
    case 'renameTable':
      return interpolate(RENAME_TABLE_SNIPPET, {
        comment: op.comment ?? `Rename table ${op.from} to ${op.to}`,
        from: quote(op.from),
        to: quote(op.to),
      });
    case 'updateRows': {
      const [firstSetColumn] = Object.keys(op.set);
      return interpolate(UPDATE_ROWS_SNIPPET, {
        comment: op.comment ?? `Update rows in ${op.table}`,
        table: quote(op.table),
        guardColumn: quote(op.guardColumn ?? firstSetColumn),
        where: renderWhere(op.where),
        set: renderObject(op.set),
      });
    }
    case 'renameColumn':
    default:
      return interpolate(RENAME_COLUMN_SNIPPET, {
        comment: op.comment ?? `Rename column ${op.table}.${op.from} to ${op.to}`,
        table: quote(op.table),
        from: quote(op.from),
        to: quote(op.to),
      });
  }
};

export const renderMigrationFile = ({
  timestamp,
  operations,
}: {
  timestamp: string;
  operations: MigrationFileOperation[];
}): string => {
  const body = operations.map(renderMigrationFileOperation).join('\n\n');
  return interpolate(JS_TEMPLATE, { timestamp, body });
};

interface BuildOptions {
  name: string;
}

interface MigrationFileBuilderDeps {
  db: Database;
}

export const createMigrationFileBuilder = ({ db }: MigrationFileBuilderDeps) => {
  const operations: MigrationFileOperation[] = [];

  const resolveMigrationsDir = (): string => {
    return (
      db.config?.settings?.migrations?.dir ?? path.join(process.cwd(), 'database', 'migrations')
    );
  };

  return {
    renameColumn(op: RenameColumnOperation): void {
      operations.push({ kind: 'renameColumn', ...op });
    },

    renameTable(op: RenameTableOperation): void {
      operations.push({ kind: 'renameTable', ...op });
    },

    updateRows(op: UpdateRowsOperation): void {
      operations.push({ kind: 'updateRows', ...op });
    },

    hasChanges(): boolean {
      return operations.length > 0;
    },

    getOperations(): MigrationFileOperation[] {
      return [...operations];
    },

    build({ name }: BuildOptions): BuiltMigrationFile | null {
      if (operations.length === 0) {
        return null;
      }

      const timestamp = getFormattedTimestamp();
      const content = renderMigrationFile({ timestamp, operations });
      const filename = `${timestamp}.${name}.js`;

      return { filename, content };
    },

    async writeFiles(options: BuildOptions): Promise<string | null> {
      const built = this.build(options);
      if (!built) {
        return null;
      }

      const dir = resolveMigrationsDir();
      await fse.ensureDir(dir);

      let filePath = path.join(dir, built.filename);
      for (let suffix = 1; await fse.pathExists(filePath); suffix += 1) {
        filePath = path.join(dir, built.filename.replace(/\.js$/, `-${suffix}.js`));
      }

      await fse.writeFile(filePath, built.content, 'utf8');

      return filePath;
    },
  };
};

export type MigrationFileBuilder = ReturnType<typeof createMigrationFileBuilder>;
