import path from 'node:path';
import fse from 'fs-extra';

import type { Database } from '..';

export interface BuiltMigrationFile {
  filename: string;
  content: string;
}

export interface RenameColumnOperation {
  table: string;
  from: string;
  to: string;
  comment?: string;
}

export interface RenameTableOperation {
  from: string;
  to: string;
  comment?: string;
}

export interface UpdateRowsOperation {
  table: string;
  where: Record<string, string>;
  set: Record<string, string>;
  guardColumn?: string;
  comment?: string;
}

export type MigrationFileOperation =
  | ({ kind: 'renameColumn' } & RenameColumnOperation)
  | ({ kind: 'renameTable' } & RenameTableOperation)
  | ({ kind: 'updateRows' } & UpdateRowsOperation);

export type MigrationFileFormat = 'javascript' | 'typescript';

const FILE_EXTENSIONS: Record<MigrationFileFormat, string> = {
  javascript: 'js',
  typescript: 'ts',
};

/**
 * Produces a sortable, filesystem-safe UTC timestamp (e.g. `2026.06.11T15.16.00.123`).
 *
 * Based on the migration generator's format but keeps milliseconds: generated
 * migrations can be written multiple times in the same second, so second
 * precision would produce colliding filenames. UTC (not local time) so that
 * files generated by developers in different time zones still sort in the
 * order they were created.
 */
export const getFormattedTimestamp = (date: Date = new Date()): string => {
  return date.toJSON().replace(/[-:]/g, '.').replace(/Z$/, '');
};

const HEADER_COMMENT = `/**
 * Auto-generated by Strapi on {{timestamp}}.
 *
 * Every step goes through the database rename helpers, which check that the
 * source table/column exists and the target does not before touching anything,
 * so this file is a safe no-op on a fresh database (the tables are created by
 * schema sync afterwards). Skipped steps are logged at startup.
 */`;

const JS_TEMPLATE = `'use strict';

${HEADER_COMMENT}
module.exports = {
  async up(knex, db) {
{{body}}
  },
  async down(knex, db) {
    // Down migrations are not generated for automatically generated migrations.
  },
};
`;

const TS_TEMPLATE = `import type { Knex } from 'knex';
import type { Core } from '@strapi/strapi';

${HEADER_COMMENT}
export default {
  async up(knex: Knex, db: Core.Strapi['db']) {
{{body}}
  },
  async down(knex: Knex, db: Core.Strapi['db']) {
    // Down migrations are not generated for automatically generated migrations.
  },
};
`;

const TEMPLATES: Record<MigrationFileFormat, string> = {
  javascript: JS_TEMPLATE,
  typescript: TS_TEMPLATE,
};

const RENAME_COLUMN_SNIPPET = `    // {{comment}}
    await db.schema.renameColumn(knex, { table: {{table}}, from: {{from}}, to: {{to}} });`;

const RENAME_TABLE_SNIPPET = `    // {{comment}}
    await db.schema.renameTable(knex, { from: {{from}}, to: {{to}} });`;

const UPDATE_ROWS_SNIPPET = `    // {{comment}}
    await db.schema.updateRows(knex, {
      table: {{table}},
      guardColumn: {{guardColumn}},
      where: {{where}},
      set: {{set}},
    });`;

const interpolate = (template: string, values: Record<string, string>): string => {
  return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_match, key: string) => {
    return key in values ? values[key] : `{{${key}}}`;
  });
};

const quote = (value: string): string =>
  `'${value.replaceAll('\\', String.raw`\\`).replaceAll("'", String.raw`\'`)}'`;

const IDENTIFIER_KEY = /^[A-Za-z_$][\w$]*$/;

const renderKey = (key: string): string => (IDENTIFIER_KEY.test(key) ? key : quote(key));

const renderObject = (values: Record<string, string>): string => {
  return `{ ${Object.entries(values)
    .map(([key, value]) => `${renderKey(key)}: ${quote(value)}`)
    .join(', ')} }`;
};

export const getOperationComment = (op: MigrationFileOperation): string => {
  if (op.comment) {
    return op.comment;
  }

  switch (op.kind) {
    case 'renameTable':
      return `Rename table ${op.from} to ${op.to}`;
    case 'updateRows':
      return `Update rows in ${op.table}`;
    case 'renameColumn':
    default:
      return `Rename column ${op.table}.${op.from} to ${op.to}`;
  }
};

export const renderMigrationFileOperation = (op: MigrationFileOperation): string => {
  const comment = getOperationComment(op);

  switch (op.kind) {
    case 'renameTable':
      return interpolate(RENAME_TABLE_SNIPPET, {
        comment,
        from: quote(op.from),
        to: quote(op.to),
      });
    case 'updateRows': {
      const [firstSetColumn] = Object.keys(op.set);
      return interpolate(UPDATE_ROWS_SNIPPET, {
        comment,
        table: quote(op.table),
        guardColumn: quote(op.guardColumn ?? firstSetColumn),
        where: renderObject(op.where),
        set: renderObject(op.set),
      });
    }
    case 'renameColumn':
    default:
      return interpolate(RENAME_COLUMN_SNIPPET, {
        comment,
        table: quote(op.table),
        from: quote(op.from),
        to: quote(op.to),
      });
  }
};

export const renderMigrationFile = ({
  timestamp,
  operations,
  format = 'javascript',
}: {
  timestamp: string;
  operations: MigrationFileOperation[];
  format?: MigrationFileFormat;
}): string => {
  const body = operations.map(renderMigrationFileOperation).join('\n\n');
  return interpolate(TEMPLATES[format], { timestamp, body });
};

interface BuildOptions {
  name: string;
  /**
   * Module format of the generated file. `typescript` emits an ES module with
   * typed `up`/`down` signatures and a `.ts` extension so the app's `tsc` build
   * compiles it into `dist/database/migrations`, which is where migrations are
   * discovered when `useTypescriptMigrations` is enabled. Defaults to
   * `javascript` (CommonJS).
   */
  format?: MigrationFileFormat;
}

interface WriteOptions extends BuildOptions {
  /**
   * Directory the migration file is written to. Defaults to the database's
   * configured migrations directory. The Content-Type Builder passes the app's
   * source `database/migrations` explicitly so the file is never written into
   * build output (e.g. `dist/` when `useTypescriptMigrations` is enabled).
   */
  dir?: string;
}

interface MigrationFileBuilderDeps {
  db: Database;
}

export const createMigrationFileBuilder = ({ db }: MigrationFileBuilderDeps) => {
  const operations: MigrationFileOperation[] = [];

  const resolveMigrationsDir = (): string => {
    return (
      db.config?.settings?.migrations?.dir ?? path.join(process.cwd(), 'database', 'migrations')
    );
  };

  return {
    renameColumn(op: RenameColumnOperation): void {
      operations.push({ kind: 'renameColumn', ...op });
    },

    renameTable(op: RenameTableOperation): void {
      operations.push({ kind: 'renameTable', ...op });
    },

    updateRows(op: UpdateRowsOperation): void {
      operations.push({ kind: 'updateRows', ...op });
    },

    hasChanges(): boolean {
      return operations.length > 0;
    },

    getOperations(): MigrationFileOperation[] {
      return [...operations];
    },

    build({ name, format = 'javascript' }: BuildOptions): BuiltMigrationFile | null {
      if (operations.length === 0) {
        return null;
      }

      const timestamp = getFormattedTimestamp();
      const content = renderMigrationFile({ timestamp, operations, format });
      const filename = `${timestamp}.${name}.${FILE_EXTENSIONS[format]}`;

      return { filename, content };
    },

    async writeFiles(options: WriteOptions): Promise<string | null> {
      const built = this.build(options);
      if (!built) {
        return null;
      }

      const dir = options.dir ?? resolveMigrationsDir();
      await fse.ensureDir(dir);

      const extension = path.extname(built.filename);
      const basename = built.filename.slice(0, -extension.length);

      let suffix = 0;
      let filePath = path.join(dir, built.filename);
      while (await fse.pathExists(filePath)) {
        suffix += 1;
        filePath = path.join(dir, `${basename}-${suffix}${extension}`);
      }

      await fse.writeFile(filePath, built.content, 'utf8');

      return filePath;
    },
  };
};

export type MigrationFileBuilder = ReturnType<typeof createMigrationFileBuilder>;
