name: 'Monorepo build (pnpm)'
description: 'Run pnpm build with cache enabled'

runs:
  using: 'composite'

  steps:
    - name: ♻️ Restore build cache
      uses: actions/cache@v4
      id: build-cache
      with:
        path: packages/**/dist
        key: pnpm-build-cache-${{ github.sha }}
    - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
      name: 📥 Run build
      shell: bash
      run: pnpm nx run-many --targets build --nx-ignore-cycles --skip-nx-cache
