// This file is auto-generated by `yarn verify:translations --write-types`.
// Do not edit manually.

import en from './en.json';

export type UploadTradKey = keyof typeof en;

export type UploadMessageId = `upload.${UploadTradKey}`;
