const RESPONSIVE_DEFAULT_SPACING = {
  initial: 4,
  medium: 6,
  large: 10,
};

const HEIGHT_TOP_NAVIGATION = '6.4rem';
const HEIGHT_TOP_NAVIGATION_MEDIUM = '5.6rem';
const WIDTH_SIDE_NAVIGATION = '23.2rem';

export {
  RESPONSIVE_DEFAULT_SPACING,
  HEIGHT_TOP_NAVIGATION,
  HEIGHT_TOP_NAVIGATION_MEDIUM,
  WIDTH_SIDE_NAVIGATION,
};
