const RESPONSIVE_DEFAULT_SPACING = {
  initial: 4,
  medium: 6,
  large: 10,
};

const HEIGHT_TOP_NAVIGATION = '6.3rem';
const HEIGHT_TOP_NAVIGATION_MEDIUM = '5.6rem';

export { RESPONSIVE_DEFAULT_SPACING, HEIGHT_TOP_NAVIGATION, HEIGHT_TOP_NAVIGATION_MEDIUM };
