// This file is auto-generated by `yarn verify:translations --write-types`.
// Do not edit manually.

import en from './en.json';

export type ContentTypeBuilderTradKey = keyof typeof en;

export type ContentTypeBuilderMessageId = `content-type-builder.${ContentTypeBuilderTradKey}`;
