/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [{ type: 'autogenerated', dirName: 'docs' }],
  api: [{ type: 'autogenerated', dirName: 'api' }],
  exports: [{ type: 'autogenerated', dirName: 'exports' }],
  guides: [{ type: 'autogenerated', dirName: 'guides' }],
  rfcs: [{ type: 'autogenerated', dirName: 'rfcs' }],
};

export default sidebars;
