import fs from 'node:fs';
import path from 'node:path';

import { readJsonRecord } from './bundles';
import type { TranslationBundle } from './types';

const toTypeName = (packageName: string) => {
  const parts = packageName.split('/').pop()!.split(/[-]/);
  return parts.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('');
};

export const generateTypesForBundle = (bundle: TranslationBundle): string => {
  const typeBase = toTypeName(bundle.packageName);
  const tradKeyType = `${typeBase}TradKey`;
  const messageIdType = bundle.pluginPrefix ? `${typeBase}MessageId` : `${typeBase}MessageId`;

  const lines = [
    '// This file is auto-generated by `yarn verify:translations --write-types`.',
    '// Do not edit manually.',
    '',
    "import en from './en.json';",
    '',
    `export type ${tradKeyType} = keyof typeof en;`,
  ];

  if (bundle.pluginPrefix) {
    lines.push('', `export type ${messageIdType} = \`${bundle.pluginPrefix}.\${${tradKeyType}}\`;`);
  } else {
    lines.push('', `export type ${messageIdType} = ${tradKeyType};`);
  }

  lines.push('');

  return lines.join('\n');
};

export const writeTypesForBundle = (bundle: TranslationBundle): boolean => {
  const outputPath = path.join(bundle.translationsDir, 'keys.generated.d.ts');
  const legacyPath = path.join(bundle.translationsDir, 'keys.generated.ts');
  const content = generateTypesForBundle(bundle);
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : null;

  if (fs.existsSync(legacyPath)) {
    fs.unlinkSync(legacyPath);
  }

  if (current === content) {
    return false;
  }

  fs.writeFileSync(outputPath, content);
  return true;
};

export const generateHelperOverload = (bundle: TranslationBundle): string | null => {
  if (!bundle.pluginPrefix) {
    return null;
  }

  const typeBase = toTypeName(bundle.packageName);
  const helperName =
    bundle.packageName === 'core/content-manager' || bundle.packageName === 'plugins/i18n'
      ? 'getTranslation'
      : 'getTrad';

  return `import type { ${typeBase}TradKey, ${typeBase}MessageId } from '../translations/keys.generated';

type AnyString = string & {};

export function ${helperName}(id: ${typeBase}TradKey): ${typeBase}MessageId;
export function ${helperName}(id: AnyString): string;
export function ${helperName}(id: string): string {
  return \`${bundle.pluginPrefix}.\${id}\`;
}
`;
};
