# =============================================================#
# StateFullSet Strapi
# =============================================================#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: strapi
  namespace: tipsoption-dev
spec:
  replicas: 1
  serviceName: svc-strapi
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: strapi
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      volumes:
        - name: env
          secret:
            secretName: strapi-secret
      containers:
        - name: strapi
          image: 973145121826.dkr.ecr.eu-west-1.amazonaws.com/tipsoption:strapi-0.0.2
          ports:
            - containerPort: 1337
              name: http
          # command: ["/bin/bash", "-c", "tail -F anything"]
          volumeMounts:
            - name: datadir
              mountPath: /opt/data
          env:
            - name: NODE_ENV
              value: development
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: jwt-secret
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: app-keys
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: api-token-salt
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: admin-jwt-secret
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: transfer-token-salt
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "1337"
            - name: DB
              value: postgres
            - name: DATABASE_CLIENT
              value: postgres
            - name: DATABASE_HOST
              value: svc-postgress
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgress-secret
                  key: database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgress-secret
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgress-secret
                  key: pwd
            - name: STRAPI_LOG_LEVEL
              value: "info"
          startupProbe:
            httpGet:
              path: /admin
              port: http
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /admin
              port: http
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: "25m"
              memory: "256Mi"
              ephemeral-storage: 128Mi
            limits:
              cpu: "100m"
              memory: "768Mi"
              ephemeral-storage: 256Mi
# =============================================================#
