'use strict';

const PROVIDER_REDIRECT_BASE = '/auth/login';
const PROVIDER_REDIRECT_SUCCESS = `${PROVIDER_REDIRECT_BASE}/success`;
const PROVIDER_REDIRECT_ERROR = `${PROVIDER_REDIRECT_BASE}/error`;

module.exports = {
  PROVIDER_REDIRECT_BASE,
  PROVIDER_REDIRECT_SUCCESS,
  PROVIDER_REDIRECT_ERROR,
};
