'use strict';

/**
 * @typedef EntryModuleArgs
 * @property {Array<{name: string; path: string; importName: string}>} plugins
 */

/**
 *
 * @param {EntryModuleArgs} arguments for the entry module creation
 * @returns {string} the `app.js` file as a string to be written to disk
 */
const getEntryModule = ({ plugins }) => {
  const pluginsObject = plugins
    .map(({ name, importName }) => `'${name}': ${importName}`)
    .join(',\n');

  const pluginsImport = plugins
    .map(({ importName, path }) => `import ${importName} from '${path}';`)
    .join('\n');

  return `
/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
${pluginsImport}

import { renderAdmin } from "@strapi/admin/admin"

renderAdmin({
    plugins: {
${pluginsObject}
    }
})
    `;
};

module.exports = { getEntryModule };
