name: Deploy contributor doc

on:
  push:
    branches:
      - 'develop'

  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

defaults:
  run:
    working-directory: docs

permissions: {}
jobs:
  deploy:
    permissions:
      contents: write # to push pages branch (peaceiris/actions-gh-pages)

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn install  --immutable

      - name: Build website
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          cname: contributor.strapi.io
