name: Label Pre-2021 Issues
on:
  workflow_dispatch: # Allows manual triggering from the Github UI

permissions:
  issues: write # Required to close issues and post comments
  contents: read # Needed by most GitHub Actions
  pull-requests: read # Needed to access PR data

jobs:
  close-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: Label old issues
        run: |
          # Set the cutoff date (issues created before this date will be labeled)
          CUTOFF_DATE="2021-01-01"
          LABEL="stale-before-2021"

          echo "Labeling issues created before $CUTOFF_DATE with $LABEL"

          # Get all open issues created before the cutoff date
          # Exclude issues with 'severity: high' or 'severity: critical' and 'issue: security' label and issues in milestones
          # NOTE: This will only process the first 100 issues due to pagination limitation
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/search/issues?q=repo:${{ github.repository }}+is:issue+is:open+created:%3C$CUTOFF_DATE+no:milestone+-label:%22severity:%20high%22+-label:%22severity:%20critical%22+-label:%22issue:%20security%22&per_page=100" | \
            jq -r --arg label "$LABEL" ' 
              .items[] | 
              select(any(.labels[]?; .name == $label) | not) |
              .number
            ' | while read issue_number; do
              if [ ! -z "$issue_number" ]; then
                echo "Labeling issue #$issue_number with $LABEL" 
                
                # Add the label
                curl -s -X POST \
                  -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/labels" \
                  -d "{\"labels\": [\"$LABEL\"]}"
                
                echo "Labeled issue #$issue_number"
              else
                echo "No issue found."
              fi
            done
