#!/usr/bin/env bash
#
# Validates a commit message against the Conventional Commits specification.
# Allowed types are kept in sync with .commitlintrc.ts.
#
# Usage: ./conventional-commits.sh <commit-msg-file>
# Ref:   https://www.conventionalcommits.org/en/v1.0.0/

set -e

COMMIT_MSG_FILE="$1"

if [ -z "$COMMIT_MSG_FILE" ] || [ ! -f "$COMMIT_MSG_FILE" ]; then
  echo "Usage: $0 <commit-msg-file>" >&2
  exit 1
fi

COMMIT_MSG=$(head -1 "$COMMIT_MSG_FILE")

# Skip GitHub-style merge commits (whitelisted in .commitlintrc.ts)
if echo "$COMMIT_MSG" | grep -qE "^Merge branch '.*' into [a-zA-Z0-9\/\-_]+$"; then
  exit 0
fi

# Skip fixup/squash commits generated by git itself
if echo "$COMMIT_MSG" | grep -qE "^(fixup|squash)! "; then
  exit 0
fi

# Types must match .commitlintrc.ts → rules → type-enum
# TODO @Nico - keep in sync manually if .commitlintrc.ts type-enum changes
ALLOWED_TYPES="chore|ci|docs|enhancement|feat|fix|release|revert|security|test|future"

# Pattern: <type>[optional scope][optional !]: <non-empty description>
PATTERN="^(${ALLOWED_TYPES})(\([^()]+\))?(!)?: .+"

if ! echo "$COMMIT_MSG" | grep -qE "$PATTERN"; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "COMMIT BLOCKED: message does not follow Conventional Commits format"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "  Got:     $COMMIT_MSG"
  echo ""
  echo "  Format:  <type>[(<scope>)][!]: <description>"
  echo "  Types:   chore | ci | docs | enhancement | feat | fix"
  echo "           release | revert | security | test | future"
  echo ""
  echo "  Examples:"
  echo "    feat(admin): add user permission system"
  echo "    fix: resolve null pointer in content-manager"
  echo "    chore!: drop Node 16 support"
  echo ""
  echo "  Spec:    https://www.conventionalcommits.org/en/v1.0.0/"
  echo "  Config:  .commitlintrc.ts"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  exit 1
fi

exit 0
